# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  workflow_dispatch:
    

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -c release --product swift-sdk-generator
    - name: copy swift-sdk
      run: cp .build/release/swift-sdk-generator .
    - name: generate linux arm sdk
      run: swift-sdk-generator make-linux-sdk --target arm64-unknown-linux-gnu --host amd64-unknown-linux-gn
    - name: generate linux amd64 sdk
      run: swift-sdk-generator make-linux-sdk --target amd64-unknown-linux-gnu --host amd64-unknown-linux-gn
